# Generated by Django 3.1.4 on 2020-12-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natapp', '0003_delete_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDC', models.CharField(max_length=64)),
                ('POOL', models.IntegerField()),
                ('IPS', models.CharField(max_length=255)),
            ],
        ),
    ]
