# Generated by Django 3.1.4 on 2020-12-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natapp', '0006_ip_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.TextField(db_index=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='IP_list',
        ),
    ]
