# Generated by Django 3.1.4 on 2020-12-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natapp', '0008_auto_20201221_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPS',
        ),
        migrations.AlterField(
            model_name='idc_ip_list',
            name='POOL1',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='idc_ip_list',
            name='POOL2',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='idc_ip_list',
            name='POOL3',
            field=models.TextField(db_index=True),
        ),
    ]
