# Generated by Django 3.1.4 on 2020-12-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natapp', '0009_auto_20201221_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDC_IP_LIST',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
